# Computação com Numpy

Notebook para anotações durante minha formação cientista de dados na data science academy na sessão do capítulo 02

## 1 - Funções, métodos e atributos

In [1]:
# Importando módulo para manipulação computacional
import numpy as np

In [2]:
# Vetor
array1 = np.array([2, 3, 5, 7]); array1

array([2, 3, 5, 7])

In [3]:
# Matriz
array2 = np.array([[1, 2, 3, 4], [2, 3, 5, 7]]); array2

array([[1, 2, 3, 4],
       [2, 3, 5, 7]])

In [4]:
# Vetor sequêncial
array3 = np.arange(7); array3

array([0, 1, 2, 3, 4, 5, 6])

In [5]:
# Vetor linear
array4 = np.linspace(1, 10, 4); array4

array([ 1.,  4.,  7., 10.])

In [6]:
# Matriz identidade
array5 = np.eye(5); array5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
# Matriz diagonal
array6 = np.diag([1, 2, 3, 4]); array6

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [8]:
# Ladrilhando uma matriz
array7 = np.tile(array6, reps=3); array7

array([[1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0],
       [0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0],
       [0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0, 4]])

In [9]:
# Vetor com zeros
array8 = np.zeros(10); array8

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# Vetor com umns
array9 = np.ones(10); array9

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
# Função de logica entre arrays

array10 = np.array([False, False, True, True])
array11 = np.array([True, False, True, False])

In [12]:
np.logical_and(array10, array11)

array([False, False,  True, False])

In [13]:
np.logical_or(array10, array11)

array([ True, False,  True,  True])

In [14]:
# Testando velocidade

np_array = np.arange(1000000)
py_array = list(range(1000000))

In [15]:
%timeit [x ** 4 for x in py_array]

452 ms ± 17 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [16]:
%timeit np_array ** 4

3.64 ms ± 147 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## 2 - Aplicando slicing em objetos numpy

In [17]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

array1 = np.array(matrix); array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
array1[:2, 1:]

array([[2, 3],
       [5, 6]])

In [19]:
array1[2, 1:]

array([8, 9])

## 3 - Transposição e reshaping de arrays

In [32]:
def np_is_prime(number):
    predecessors = np.arange(2, number, 1)
    return not np.any((number % predecessors) == 0)

def py_is_prime(number):
    predecessors = list(range(2, number, 1))
    for precessor in predecessors:
        if (number % precessor) == 0:
            return False
    return True

In [43]:
%timeit np_is_prime(1330207)

33.6 ms ± 1.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [44]:
%timeit py_is_prime(1330207)

193 ms ± 12.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
