# Slicing com Numpy

In [1]:
# Importando o módulo numpy
import numpy as np

In [2]:
# Criando um array unidimensional
array1 = np.array([2, 3, 5, 7, 11]); array1

array([ 2,  3,  5,  7, 11])

In [3]:
# Escolhendo o elemento de index 3 do array (ou posição 4°)
array1[3]

7

In [4]:
# Trocando o valor do array através de acesso ao atributo
array1[3] = 5; array1

array([ 2,  3,  5,  5, 11])

In [5]:
# Craindo um array bidimensional
array2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [11, 13, 15, 19]]); array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 13, 15, 19]])

In [6]:
# Acessando elementos que estão simultaneamente na linha 0 e 1, e na coluna 2 e 3
array2[0:2, 2:4]

array([[3, 4],
       [7, 8]])

In [7]:
# Criando um array de multiplos de 2
array3 = np.arange(50) * 2; array3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [8]:
# Indo do index 0, ao index 20, pulando de 5 em 5
array3[0:20:5]

array([ 0, 10, 20, 30])

In [9]:
# Retorna todos os elementos até o elemento de index 10
array3[:10]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# Retorna todos os elementos do index 10 em diante
array3[10:]

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86,
       88, 90, 92, 94, 96, 98])

In [11]:
# Criando uma função para retornar múltiplos de um número
def multiples(x, limit=100):
    array = np.arange(limit)
    return array[::x]

In [13]:
multiples(7, 100)

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [12]:
# Podemos alterar o array principal pelo atributo do index
array3[5:] = 0; array3

array([0, 2, 4, 6, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [14]:
array4 = np.array([2, 3, 5, 7, 11]); array4

array([ 2,  3,  5,  7, 11])

In [17]:
array4[::-1]

array([11,  7,  5,  3,  2])

In [18]:
inverte_array = lambda array : array[::-1]

In [19]:
inverte_array(array4)

array([11,  7,  5,  3,  2])