# Computação e Álgebra Linear com Numpy

In [42]:
# Importando o módulo numpy
import numpy as np

In [43]:
# Criando um array de 1 dimensão (unidimensional)
array1 = np.array([2, 3, 5, 7]); array1

array([2, 3, 5, 7])

In [44]:
# Criando um array de 2 dimensões (bidimensional)
array2 = np.array([[2, 3, 5, 7], [1, 2, 3, 4]]); array2

array([[2, 3, 5, 7],
       [1, 2, 3, 4]])

In [45]:
# Verificando o formato atráves do atributo shape
array2.shape

(2, 4)

In [46]:
# Número de dimensões atráves do atributo ndim
array2.ndim

2

In [47]:
# Verificando o maior elemento atráves do método max
array2.max()

7

In [48]:
# Criando a matriz transposta atráves do atributo T
array2.T

array([[2, 1],
       [3, 2],
       [5, 3],
       [7, 4]])

In [49]:
# Criando um vetor com elementos inteiros
array3 = np.arange(15); array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
# Verificando maiores parâmetros do método arange
array4 = np.arange(0,15, 5); array4

array([ 0,  5, 10])

In [51]:
# Criando um array linear
array5 = np.linspace(0, 10, 5); array5 # Números de 0 a 10, contendo 5 elementos

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [52]:
# Criando um array (ou matriz) atráves da função zeros
array6 = np.zeros((5, 6)); array6 # 5 Linhas por 6 colunas

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [53]:
# Criando um array (ou matriz) atráves da função ones
array7 = np.ones((5, 6)); array7 # 5 Linhas por 6 colunas

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [54]:
# Criando uma matriz identidade
array8 = np.eye(6); array8

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [55]:
# Criando uma matriz com a diagonal personalizada
array9 = np.diag([2, 3, 5, 7]); array9

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

In [56]:
# Criando um vetor de números aleatórios
array10 = np.random.rand(5); array10

array([0.62550925, 0.58141958, 0.68620195, 0.92628952, 0.01990592])

In [57]:
# Criando um vetor de números aleatórios em distribuição normal
array11 = np.random.randn(5); array11

array([ 0.45544472,  0.26730375,  1.70010805,  0.74519093, -0.40252662])

In [64]:
# Criando uma matriz vazia
array12 = np.empty((3, 2)); array12

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [71]:
# Criando array para o próximo exemplo
array13 = np.array([[2, 3, 5, 7], [11, 13, 17, 19]]); array13

# Fazendo ladrilhos com o array acima
np.tile(array13, (2, 2))

array([[ 2,  3,  5,  7,  2,  3,  5,  7],
       [11, 13, 17, 19, 11, 13, 17, 19],
       [ 2,  3,  5,  7,  2,  3,  5,  7],
       [11, 13, 17, 19, 11, 13, 17, 19]])

In [74]:
# Utilizando o parâmetro dtype para definir os tipos dos elementos do array
array14 = np.array([2, 3, 5, 7], dtype = 'float'); array14

array([2., 3., 5., 7.])

In [76]:
# Visualizando o dtype do tipo string
array15 = np.array(['Python', 'is', 'amazing!']); array15.dtype

dtype('<U8')

In [77]:
# Criando array do tipo booleano
array16 = np.array([True, False, True, False]); array16.dtype

dtype('bool')

In [79]:
# Convertendo arrays para outro tipo de dado
array17 = array16.astype(int); array17

array([1, 0, 1, 0])

In [82]:
# Operações com arrays
array18 = np.arange(0, 100, 20)

# Multipicando todos os elementos por 5
array18 * 5

array([  0, 100, 200, 300, 400])

In [84]:
# Também é possível utilizar a operação de potenciação
array18 ** 4

array([       0,   160000,  2560000, 12960000, 40960000])

In [86]:
# Somando 1 a cada elemento do array
array18 + 1

array([ 1, 21, 41, 61, 81])

In [87]:
# Números pares de 0 a 20
array19 = np.arange(0, 20, 2); array19

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [90]:
# Números ímpares de 0 a 20
array20 = np.arange(1, 20, 2); array20

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [91]:
# Soma com arrays
array19 + array20 

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37])

In [94]:
# Subtração com arrays
array20 - array19

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [95]:
# Multiplicação de arrays
array19 * array20

array([  0,   6,  20,  42,  72, 110, 156, 210, 272, 342])

In [97]:
# Divisão de arrays
array19 / array20

array([0.        , 0.66666667, 0.8       , 0.85714286, 0.88888889,
       0.90909091, 0.92307692, 0.93333333, 0.94117647, 0.94736842])

In [98]:
# Comparando arrays
array19 > array20

array([False, False, False, False, False, False, False, False, False,
       False])

In [99]:
# Comparando arrays
array19 < array20

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [101]:
# Criando arrays python e numpy para comparação
array_python = range(1000000)
array_numpy = np.arange(1000000)

In [104]:
# Testando a velocidade do python
%timeit [x ** 4 for x in array_python]

621 ms ± 14.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [103]:
# Testando a velocidade do numpy
%timeit array_numpy ** 4

5.91 ms ± 143 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
