In [15]:
# Importando módulo para cálculos matemáticos
import numpy as np

In [18]:
# Declarando uma matriz
matrix1 = np.matrix([[2, 2, 2], [2, 2, 2]])

# Multiplicando matriz por uma constante
matrix2 = matrix1 * 2

# Soma de matrizes
matrix1 + matrix2

matrix([[6, 6, 6],
        [6, 6, 6]])

In [19]:
# Explorando matriz 1
matrix1

matrix([[2, 2, 2],
        [2, 2, 2]])

In [20]:
# Explorando matriz 2
matrix2

matrix([[4, 4, 4],
        [4, 4, 4]])

In [30]:
# Matriz transporta
matrix2.T

matrix([[4, 4],
        [4, 4],
        [4, 4]])

In [29]:
# Multiplicação de matrizes
matrix1 * matrix2.T

matrix([[24, 24],
        [24, 24]])