In [1]:
import pandas as pd

In [2]:
dados = pd.read_csv('customer-tratado.csv')
dados = dados.drop(['Unnamed: 0'], axis = 1)

dados.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   
3               45        42.30                            0   
4                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  ...  StreamingDeFilmes_Nao  \
0                                             1  ...                      1   
1                                             0  ...                      1   
2                                             0  ...                      1   
3                                             1  ...                      1   
4                                             0  ...                      1   

   StreamingDeFilmes_SemServicoDeInternet  StreamingDeFilmes_Sim  \
0                                       0                      0   
1                                       0                      0   
2                                       0                      0   
3                                       0                      0   
4                                       0                      0   

   TipoDeContrato_DoisAnos  TipoDeContrato_Mensalmente  TipoDeContrato_UmAno  \
0                        0                           1                     0   
1                        0                           0                     1   
2                        0                           1                     0   
3                        0                           0                     1   
4                        0                           1                     0   

   FormaDePagamento_CartaoDeCredito  FormaDePagamento_ChequeDigital  \
0                                 0                               1   
1                                 0                               0   
2                                 0                               0   
3                                 0                               0   
4                                 0                               1   

   FormaDePagamento_ChequePapel  FormaDePagamento_DebitoEmConta  
0                             0                               0  
1                             1                               0  
2                             1                               0  
3                             0                               1  
4                             0                               0  

[5 rows x 39 columns]

In [3]:
xmaria = [[0,0,1,1,0,0,39.90,1,0,0,0,1,0,0,0,0,1,1,1,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,1,0,1,0]]

In [4]:
# Divisão entre input e output

x = dados.drop(['Churn'], axis = 1)
y = dados['Churn']

In [5]:
from sklearn.preprocessing import StandardScaler

norm = StandardScaler()

x_normalizado = norm.fit_transform(x)
x_normalizado[0]

array([ 1.03453023, -0.65401193, -3.05401039,  0.8297975 , -0.43991649,
       -1.27744458, -1.16032292, -0.96332984,  3.05401039, -0.85417615,
        1.38171215, -0.88565976, -0.52592737,  1.00669571, -0.52592737,
       -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
       -0.52592737, -0.72396752,  1.0138687 , -0.52592737, -0.63943864,
        1.2273572 , -0.52592737, -0.79013171,  1.23648892, -0.52592737,
       -0.79607014, -0.56297505,  0.90418382, -0.51424938, -0.52504733,
        1.40641839, -0.54480692, -0.5298852 ])

In [6]:
xmaria_normalizado = norm.transform(pd.DataFrame(xmaria, columns = x.columns))
xmaria_normalizado

array([[-0.96662231, -0.65401193,  0.32743831,  0.8297975 , -0.43991649,
        -1.31816495, -0.82630172,  1.03806605, -0.32743831, -0.85417615,
        -0.72373975,  1.12910177, -0.52592737, -0.99334883, -0.52592737,
        -0.63393298,  1.13170855,  1.90140322,  1.3782406 , -0.88540456,
        -0.52592737,  1.38127743,  1.0138687 , -0.52592737, -0.63943864,
        -0.81475874, -0.52592737,  1.26561178, -0.80874158, -0.52592737,
         1.25617071, -0.56297505, -1.1059698 , -0.51424938,  1.90459021,
        -0.71102597,  1.83551265, -0.5298852 ]])

In [7]:
import numpy as np

a = xmaria_normalizado
b = x_normalizado[0]

a - b

array([[-2.00115254,  0.        ,  3.3814487 ,  0.        ,  0.        ,
        -0.04072036,  0.3340212 ,  2.00139589, -3.3814487 ,  0.        ,
        -2.10545189,  2.01476153,  0.        , -2.00004453,  0.        ,
         0.        ,  2.01532828,  2.42733059,  0.        , -2.01483177,
         0.        ,  2.10524495,  0.        ,  0.        ,  0.        ,
        -2.04211593,  0.        ,  2.05574349, -2.0452305 ,  0.        ,
         2.05224086,  0.        , -2.01015362,  0.        ,  2.42963754,
        -2.11744436,  2.38031958,  0.        ]])

In [8]:
np.square(a - b)

array([[4.00461149e+00, 0.00000000e+00, 1.14341953e+01, 0.00000000e+00,
        0.00000000e+00, 1.65814802e-03, 1.11570160e-01, 4.00558550e+00,
        1.14341953e+01, 0.00000000e+00, 4.43292768e+00, 4.05926401e+00,
        0.00000000e+00, 4.00017814e+00, 0.00000000e+00, 0.00000000e+00,
        4.06154807e+00, 5.89193381e+00, 0.00000000e+00, 4.05954705e+00,
        0.00000000e+00, 4.43205631e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 4.17023749e+00, 0.00000000e+00, 4.22608130e+00,
        4.18296779e+00, 0.00000000e+00, 4.21169253e+00, 0.00000000e+00,
        4.04071758e+00, 0.00000000e+00, 5.90313856e+00, 4.48357062e+00,
        5.66592128e+00, 0.00000000e+00]])

In [9]:
np.sum(np.square(a - b))

98.81359814827535

In [10]:
np.sqrt(98.81359814827535)

9.940502912241179

In [11]:
from sklearn.model_selection import train_test_split

xtreino, xteste, ytreino, yteste = train_test_split(x_normalizado, y, test_size = 0.3, random_state=123)

In [12]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(metric='euclidean')
knn.fit(xtreino, ytreino)

KNeighborsClassifier(metric='euclidean')

In [13]:
predito_knn = knn.predict(xteste)

In [14]:
predito_knn

array([1, 0, 0, ..., 0, 0, 0])

In [15]:
np.median(xtreino)

-0.5259273725834717

In [16]:
from sklearn.naive_bayes import BernoulliNB

bnb = BernoulliNB(binarize=-0.52)
bnb.fit(xtreino, ytreino)
predito_bnb = bnb.predict(xteste)
predito_bnb

array([1, 0, 0, ..., 0, 1, 0])

In [17]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(yteste, predito_knn))

[[1302  221]
 [ 317  273]]


In [18]:
print(confusion_matrix(yteste, predito_bnb))

[[1045  478]
 [ 117  473]]


In [19]:
from sklearn.metrics import accuracy_score

print(accuracy_score(yteste, predito_knn))
print(accuracy_score(yteste, predito_bnb))

0.7453857075248462
0.718409843823947


In [20]:
from sklearn.metrics import precision_score

print(precision_score(yteste, predito_knn))
print(precision_score(yteste, predito_bnb))

0.5526315789473685
0.49737118822292326


In [21]:
from sklearn.metrics import recall_score

print(recall_score(yteste, predito_knn))
print(recall_score(yteste, predito_bnb))

0.46271186440677964
0.8016949152542373
