In [1]:
import numpy as np

In [4]:
# Numpy permite a criação de arange semelhante a função bult-in range
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
quilometros_lista = [44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,]

In [6]:
quilometros_lista

[44410,
 5712,
 37123,
 0,
 25757,
 10728,
 0,
 77599,
 99197,
 37978,
 12859,
 8052,
 89773,
 0,
 41457,
 115607,
 46449,
 0,
 37086,
 15173,
 101193,
 0,
 98079,
 102959,
 0,
 0,
 5795,
 0,
 58848,
 94381,
 30163,
 53332]

In [7]:
# Numpy também permite a criação de um array numpy a partir de uma lista pela função array.
quilometros = np.array(quilometros_lista)

In [8]:
quilometros

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332])

In [9]:
# A propriedade shape mostra uma tupla com as dimensões do array numpy
quilometros.shape

(32,)

In [11]:
# O numpy consegue ser muito mais rápido que uma lista python:

In [28]:
array1 = np.arange(1000000)
array2 = list(range(1000000))

In [29]:
%time for _ in range(100): array1 *= 2

CPU times: user 1.67 s, sys: 260 µs, total: 1.67 s
Wall time: 1.67 s


In [30]:
%time for _ in range(100): array2 = [x * 2 for x in array2]

CPU times: user 11.2 s, sys: 1.29 s, total: 12.5 s
Wall time: 12.5 s


In [46]:
ano_de_fabricacao = np.array([2003, 2006, 2009, 2012, 2015, 2019])
quilometros = np.array([1000, 2000, 3000, 4000, 5000, 6000])
valor = np.array([60300, 10900, 32005, 64640, 32500, 10555])

In [37]:
idade = 2022 - ano_de_fabricacao

In [38]:
idade

array([19, 16, 13, 10,  7,  3])

In [40]:
quilometragem_media = quilometros / idade
quilometragem_media

array([  52.63157895,  125.        ,  230.76923077,  400.        ,
        714.28571429, 2000.        ])

In [42]:
data = np.array([quilometros, ano_de_fabricacao])

In [43]:
data

array([[1000, 2000, 3000, 4000, 5000, 6000],
       [2003, 2006, 2009, 2012, 2015, 2019]])

In [44]:
idade = data[0] / (2022 - data[1])

In [45]:
idade

array([  52.63157895,  125.        ,  230.76923077,  400.        ,
        714.28571429, 2000.        ])

In [49]:
# Calcula a média de um "vetor" na matriz
dataset = np.column_stack((ano_de_fabricacao, quilometros, valor))

In [50]:
dataset

array([[ 2003,  1000, 60300],
       [ 2006,  2000, 10900],
       [ 2009,  3000, 32005],
       [ 2012,  4000, 64640],
       [ 2015,  5000, 32500],
       [ 2019,  6000, 10555]])

In [51]:
np.mean(dataset, axis = 0)

array([ 2010.66666667,  3500.        , 35150.        ])

In [52]:
np.sum(dataset, axis = 0)

array([ 12064,  21000, 210900])

In [54]:
np.sum(dataset[:, 1])

21000