In [2]:
import numpy as np

In [7]:
numpy_arange = np.arange(100)

In [11]:
numpy_array = np.array(list(range(100)))

In [15]:
quilometros = np.loadtxt(fname = "data/carros-km.txt", dtype = int)

In [17]:
quilometros

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [18]:
type(quilometros)

numpy.ndarray

In [19]:
dtype(quilometros)

NameError: name 'dtype' is not defined

In [20]:
np.dtype(quilometros)

TypeError: Cannot construct a dtype from an array

In [21]:
quilometros.dtype

dtype('int64')

In [22]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]

In [23]:
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [24]:
acessorios = np.array(dados)

In [25]:
acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [26]:
acessorios.shape

(3, 8)

In [27]:
type(acessorios.type)

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [28]:
type(acessorios.shape)

tuple

In [29]:
quilometros.shape

(258,)

In [30]:
type(quilometros.shape)

tuple

In [31]:
%time print("Hello, World!")

Hello, World!
CPU times: user 86 µs, sys: 6 µs, total: 92 µs
Wall time: 101 µs


In [32]:
np_array = np.arange(1000000)
py_list = list(range(1000000))

In [33]:
%time for _ in range(100): np_array *= 2

CPU times: user 163 ms, sys: 128 µs, total: 163 ms
Wall time: 173 ms


In [35]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: user 10.4 s, sys: 1.31 s, total: 11.7 s
Wall time: 11.7 s


In [36]:
integer_numbers = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
square_numbers = integer_numbers ** 2

In [40]:
square_numbers

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
quilometros

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [47]:
ano_de_fabricacao = np.loadtxt(fname = "data/carros-anos.txt")

In [48]:
ano_de_fabricacaos

NameError: name 'ano_de_fabricacaos' is not defined

In [49]:
ano_de_fabricacao

array([2003., 1991., 1990., 2019., 2006., 2012., 2019., 2009., 2010.,
       2011., 2002., 2007., 2001., 2019., 2009., 2016., 2012., 2019.,
       2016., 2017., 2002., 2019., 1994., 1991., 2019., 2019., 2016.,
       2019., 2002., 1991., 1997., 1995., 2018., 1991., 2014., 1995.,
       2019., 2019., 2009., 2019., 2013., 2003., 2019., 2002., 2019.,
       2002., 2004., 2001., 2019., 2003., 2009., 2006., 2000., 2006.,
       2010., 1994., 2007., 2019., 2019., 2019., 2019., 2019., 2017.,
       2011., 2001., 1996., 2019., 1994., 2019., 2007., 1994., 2007.,
       1997., 2006., 2013., 1994., 2008., 2008., 2019., 2019., 1999.,
       2007., 1993., 1995., 2019., 2019., 2016., 2011., 2019., 2002.,
       2013., 2017., 2016., 2008., 2018., 2003., 2003., 2004., 2010.,
       2019., 2006., 2001., 2019., 2015., 2018., 2017., 1992., 2001.,
       1993., 1995., 2003., 2014., 2008., 2013., 2019., 2017., 2019.,
       2019., 2006., 2015., 2007., 2005., 2017., 1998., 2019., 1999.,
       2019., 2009.,

In [50]:
idade = 2022 - ano_de_fabricacao

In [51]:
idade

array([19., 31., 32.,  3., 16., 10.,  3., 13., 12., 11., 20., 15., 21.,
        3., 13.,  6., 10.,  3.,  6.,  5., 20.,  3., 28., 31.,  3.,  3.,
        6.,  3., 20., 31., 25., 27.,  4., 31.,  8., 27.,  3.,  3., 13.,
        3.,  9., 19.,  3., 20.,  3., 20., 18., 21.,  3., 19., 13., 16.,
       22., 16., 12., 28., 15.,  3.,  3.,  3.,  3.,  3.,  5., 11., 21.,
       26.,  3., 28.,  3., 15., 28., 15., 25., 16.,  9., 28., 14., 14.,
        3.,  3., 23., 15., 29., 27.,  3.,  3.,  6., 11.,  3., 20.,  9.,
        5.,  6., 14.,  4., 19., 19., 18., 12.,  3., 16., 21.,  3.,  7.,
        4.,  5., 30., 21., 29., 27., 19.,  8., 14.,  9.,  3.,  5.,  3.,
        3., 16.,  7., 15., 17.,  5., 24.,  3., 23.,  3., 13., 19., 28.,
        3., 28.,  3.,  7., 26., 25., 29.,  3., 30., 27.,  3., 32.,  3.,
        3., 31., 32., 10., 15.,  9., 22., 20., 26., 26.,  7., 29.,  9.,
        9., 13.,  3.,  3., 20., 25., 24., 18., 26.,  7.,  6., 17., 23.,
       27., 29., 18.,  9., 24.,  4.,  3.,  4.,  3., 32., 13., 32

In [53]:
quilometragem_media = quilometros / idade

In [54]:
quilometragem_media

array([2.33736842e+03, 1.84258065e+02, 1.16009375e+03, 0.00000000e+00,
       1.60981250e+03, 1.07280000e+03, 0.00000000e+00, 5.96915385e+03,
       8.26641667e+03, 3.45254545e+03, 6.42950000e+02, 5.36800000e+02,
       4.27490476e+03, 0.00000000e+00, 3.18900000e+03, 1.92678333e+04,
       4.64490000e+03, 0.00000000e+00, 6.18100000e+03, 3.03460000e+03,
       5.05965000e+03, 0.00000000e+00, 3.50282143e+03, 3.32125806e+03,
       0.00000000e+00, 0.00000000e+00, 9.65833333e+02, 0.00000000e+00,
       2.94240000e+03, 3.04454839e+03, 1.20652000e+03, 1.97525926e+03,
       4.43000000e+03, 1.09058065e+03, 1.13355000e+04, 1.62870370e+03,
       0.00000000e+00, 0.00000000e+00, 4.25076923e+02, 0.00000000e+00,
       1.03794444e+04, 2.14536842e+03, 0.00000000e+00, 4.31510000e+03,
       0.00000000e+00, 4.87750000e+02, 3.88583333e+03, 1.14047619e+02,
       0.00000000e+00, 4.22889474e+03, 6.58107692e+03, 3.15600000e+03,
       3.07800000e+03, 5.87168750e+03, 2.94541667e+03, 2.89310714e+03,
      

In [55]:
data = np.array(quilometros, ano_de_fabricacao)

TypeError: Cannot construct a dtype from an array

In [56]:
data = np.array([quilometros, ano_de_fabricacao])

In [57]:
data

array([[4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
        1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
        1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
        1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
        1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
        0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
        3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
        4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
        9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
        9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
        8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
        8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
        9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00

In [77]:
quilometragem_media = data[0] / (2022 - data[1])

In [60]:
quilometragem_mediai

NameError: name 'quilometragem_mediai' is not defined

In [78]:
quilometragem_media

array([2.33736842e+03, 1.84258065e+02, 1.16009375e+03, 0.00000000e+00,
       1.60981250e+03, 1.07280000e+03, 0.00000000e+00, 5.96915385e+03,
       8.26641667e+03, 3.45254545e+03, 6.42950000e+02, 5.36800000e+02,
       4.27490476e+03, 0.00000000e+00, 3.18900000e+03, 1.92678333e+04,
       4.64490000e+03, 0.00000000e+00, 6.18100000e+03, 3.03460000e+03,
       5.05965000e+03, 0.00000000e+00, 3.50282143e+03, 3.32125806e+03,
       0.00000000e+00, 0.00000000e+00, 9.65833333e+02, 0.00000000e+00,
       2.94240000e+03, 3.04454839e+03, 1.20652000e+03, 1.97525926e+03,
       4.43000000e+03, 1.09058065e+03, 1.13355000e+04, 1.62870370e+03,
       0.00000000e+00, 0.00000000e+00, 4.25076923e+02, 0.00000000e+00,
       1.03794444e+04, 2.14536842e+03, 0.00000000e+00, 4.31510000e+03,
       0.00000000e+00, 4.87750000e+02, 3.88583333e+03, 1.14047619e+02,
       0.00000000e+00, 4.22889474e+03, 6.58107692e+03, 3.15600000e+03,
       3.07800000e+03, 5.87168750e+03, 2.94541667e+03, 2.89310714e+03,
      

In [64]:
pesos = np.array([45, 60, 80, 100, 70])
alturas = np.array([1.55, 1.69, 1.75, 1.89, 1.73])

In [66]:
imc = pesos / (alturas ** 2)

In [67]:
imc

array([18.73048907, 21.0076678 , 26.12244898, 27.99473699, 23.38868656])

In [68]:
quilometros = [2000, 1000, 3000, 40000, 5000]
ano_de_fabricacao = [2003, 2019, 1990, 2004, 2021]

In [80]:
dados = np.array([quilometros, ano_de_fabricacao])

In [71]:
np_array

array([[ 2000,  1000,  3000, 40000,  5000],
       [ 2003,  2019,  1990,  2004,  2021]])

In [75]:
quilometragem_media = np_array[0] / (2022 - np_array[1])

In [76]:
quilometragem_media

array([ 105.26315789,  333.33333333,   93.75      , 2222.22222222,
       5000.        ])

In [79]:
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [81]:
dados

array([[ 2000,  1000,  3000, 40000,  5000],
       [ 2003,  2019,  1990,  2004,  2021]])

In [82]:
contador = np.arange(10)

In [83]:
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [86]:
maiores_que_cinco = contador[contador > 5]

In [87]:
maiores_que_cinco

array([6, 7, 8, 9])

In [97]:
dados = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteira', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casada', 'feminino']
    ]
)

In [99]:
dados[0::2, :2]

array([['Roberto', 'casado'],
       ['Bruno', 'solteiro']], dtype='<U9')

In [108]:
contador = np.arange(10)

In [101]:
contador

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [109]:
contador.reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [110]:
km

NameError: name 'km' is not defined

In [111]:
dados = [
    [48285, 20584, 10594, 92754, 0],
    [2003, 2006, 2009, 2019, 2021]
]

In [112]:
dados

[[48285, 20584, 10594, 92754, 0], [2003, 2006, 2009, 2019, 2021]]

In [113]:
dados = np.array(dados)

In [114]:
dados

array([[48285, 20584, 10594, 92754,     0],
       [ 2003,  2006,  2009,  2019,  2021]])

In [115]:
dados_new = dados.copy()

In [116]:
dados_new

array([[48285, 20584, 10594, 92754,     0],
       [ 2003,  2006,  2009,  2019,  2021]])

In [118]:
dados_new.resize((3, 5), refcheck=False)

In [119]:
dados_new

array([[48285, 20584, 10594, 92754,     0],
       [ 2003,  2006,  2009,  2019,  2021],
       [    0,     0,     0,     0,     0]])

In [121]:
dados_new[2] = dados_new[0] / (2022 - dados_new[1]) 

In [122]:
dados_new

array([[48285, 20584, 10594, 92754,     0],
       [ 2003,  2006,  2009,  2019,  2021],
       [ 2541,  1286,   814, 30918,     0]])

In [123]:
anos = np.loadtxt(fname="data/carros-anos.txt")
km = np.loadtxt(fname="data/carros-km.txt")
valor = np.loadtxt(fname="data/carros-valor.txt")

In [124]:
anos.shape

(258,)

In [125]:
anos

array([2003., 1991., 1990., 2019., 2006., 2012., 2019., 2009., 2010.,
       2011., 2002., 2007., 2001., 2019., 2009., 2016., 2012., 2019.,
       2016., 2017., 2002., 2019., 1994., 1991., 2019., 2019., 2016.,
       2019., 2002., 1991., 1997., 1995., 2018., 1991., 2014., 1995.,
       2019., 2019., 2009., 2019., 2013., 2003., 2019., 2002., 2019.,
       2002., 2004., 2001., 2019., 2003., 2009., 2006., 2000., 2006.,
       2010., 1994., 2007., 2019., 2019., 2019., 2019., 2019., 2017.,
       2011., 2001., 1996., 2019., 1994., 2019., 2007., 1994., 2007.,
       1997., 2006., 2013., 1994., 2008., 2008., 2019., 2019., 1999.,
       2007., 1993., 1995., 2019., 2019., 2016., 2011., 2019., 2002.,
       2013., 2017., 2016., 2008., 2018., 2003., 2003., 2004., 2010.,
       2019., 2006., 2001., 2019., 2015., 2018., 2017., 1992., 2001.,
       1993., 1995., 2003., 2014., 2008., 2013., 2019., 2017., 2019.,
       2019., 2006., 2015., 2007., 2005., 2017., 1998., 2019., 1999.,
       2019., 2009.,

In [126]:
dataset = np.column_stack((anos, km, valor))

In [127]:
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [128]:
dataset.shape

(258, 3)

In [135]:
np.mean(dataset, axis = 0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [136]:
np.sum(dataset)

37530599.379999995

In [137]:
np.sum(dataset, 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [139]:
np.sum(dataset[:, 1])

11480849.0