In [1]:
import numpy as np

## **Transposição e Reshaping de Arrays**

In [2]:
lista = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

array1 = np.array(lista)

In [3]:
array1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [4]:
array1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## **Broadcasting**

In [5]:
array2 = np.array([32, 69, 10])

In [6]:
array2.T + array2

array([ 64, 138,  20])

In [7]:
array2.T

array([32, 69, 10])

## Transformando matrizes em arrays

In [8]:
array3 = np.array([np.arange(1,6), np.arange(10, 15)])

In [9]:
array3

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [10]:
array3.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [11]:
array3.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

In [12]:
array4 = np.random.randint(100, 999, size = (10, 10))

In [13]:
np.any(array4 % 7 == 0)

True

In [14]:
np.all(array4 < 11)

False

In [15]:
np.all(array4 < 1000)

True

## Reshaping

In [24]:
array5 = np.random.randint(10, 99, size = (1, 100))

In [25]:
array5

array([[62, 63, 61, 96, 11, 50, 55, 32, 26, 37, 54, 53, 45, 91, 46, 96,
        60, 45, 72, 45, 35, 15, 31, 72, 44, 24, 25, 54, 16, 14, 64, 95,
        89, 65, 98, 22, 81, 72, 40, 95, 69, 27, 18, 98, 84, 14, 15, 12,
        81, 96, 13, 57, 94, 71, 52, 71, 62, 47, 30, 75, 33, 69, 22, 60,
        81, 17, 85, 46, 78, 41, 31, 24, 31, 66, 22, 95, 91, 66, 56, 39,
        11, 73, 54, 10, 85, 43, 81, 91, 25, 33, 91, 89, 26, 61, 93, 59,
        68, 43, 49, 19]])

In [27]:
array5.reshape(10, 10)

array([[62, 63, 61, 96, 11, 50, 55, 32, 26, 37],
       [54, 53, 45, 91, 46, 96, 60, 45, 72, 45],
       [35, 15, 31, 72, 44, 24, 25, 54, 16, 14],
       [64, 95, 89, 65, 98, 22, 81, 72, 40, 95],
       [69, 27, 18, 98, 84, 14, 15, 12, 81, 96],
       [13, 57, 94, 71, 52, 71, 62, 47, 30, 75],
       [33, 69, 22, 60, 81, 17, 85, 46, 78, 41],
       [31, 24, 31, 66, 22, 95, 91, 66, 56, 39],
       [11, 73, 54, 10, 85, 43, 81, 91, 25, 33],
       [91, 89, 26, 61, 93, 59, 68, 43, 49, 19]])

## Adicionando uma dimensão

In [31]:
array6 = np.random.randint(10, 99, size = (5, 10))

In [37]:
array6.sort(axis = 1)
array6

array([[10, 12, 21, 37, 44, 57, 59, 65, 68, 89],
       [11, 18, 22, 39, 53, 59, 62, 67, 81, 92],
       [14, 20, 28, 42, 54, 63, 63, 79, 94, 95],
       [26, 35, 35, 45, 57, 68, 71, 79, 94, 95],
       [30, 37, 38, 50, 68, 81, 88, 88, 94, 96]])