In [1]:
# Importando o módulo numpy
import numpy as np

In [2]:
# Instânciando um objeto do tipo array numpy
array1 = np.array([[1, 2, 3], [4, 5, 6]]); array1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# Acessando o atributo que guarda a transposta da matriz
array1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
# Utilizando o método numpy para fazer a transposta da matriz
np.transpose(array1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
# Criando uma função para verificar se uma matriz é simétrica
matrix_is_symmetric = lambda matrix : np.all((np.transpose(matrix) == matrix))
                                            
# Criando uma matrix simétrica
A = np.array([
    [5, 1, 2],
    [1, 6, 3],
    [2, 3, 8]
])

# Verificando se a matriz é simétrica
matrix_is_symmetric(A)

True

In [6]:
# Criando um array bidimensional qualquer
array2 = np.array([range(5), range(5, 10)]); array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
# Planificando uma matriz
array2.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Criando uma matriz de valores aleatorios
array3 = np.random.randint(0, 10, size=(4, 4)); array3

array([[7, 1, 7, 0],
       [9, 3, 5, 3],
       [6, 1, 2, 6],
       [3, 0, 1, 2]])

In [9]:
np.all(array3 < 11)

True

In [12]:
# Ordenando o nosso array
array4 = np.random.randint(0, 10, size=(5, 5)); array4

array([[6, 5, 2, 7, 7],
       [9, 6, 8, 7, 9],
       [8, 6, 2, 6, 2],
       [9, 3, 2, 7, 9],
       [0, 3, 6, 9, 2]])

In [16]:
# Ordenando pelas colunas
array4.sort(axis=0); array4

array([[0, 2, 3, 6, 7],
       [2, 2, 6, 6, 8],
       [2, 3, 6, 7, 9],
       [2, 5, 7, 9, 9],
       [6, 7, 8, 9, 9]])

In [17]:
array5 = np.random.randint(0, 10, size=(10, 10)); array5

array([[7, 6, 3, 0, 7, 9, 2, 5, 1, 9],
       [5, 7, 2, 6, 7, 4, 2, 0, 5, 0],
       [7, 1, 7, 9, 2, 2, 3, 4, 3, 7],
       [3, 3, 9, 7, 9, 5, 3, 5, 9, 0],
       [1, 1, 5, 6, 2, 6, 4, 7, 3, 1],
       [8, 3, 3, 2, 6, 4, 6, 3, 6, 3],
       [4, 9, 2, 0, 2, 5, 9, 0, 5, 0],
       [5, 1, 6, 1, 6, 3, 3, 3, 0, 6],
       [8, 8, 1, 8, 1, 2, 7, 0, 9, 5],
       [2, 2, 0, 6, 6, 9, 9, 7, 7, 8]])

In [18]:
np.reshape(array5, newshape=(5, 20))

array([[7, 6, 3, 0, 7, 9, 2, 5, 1, 9, 5, 7, 2, 6, 7, 4, 2, 0, 5, 0],
       [7, 1, 7, 9, 2, 2, 3, 4, 3, 7, 3, 3, 9, 7, 9, 5, 3, 5, 9, 0],
       [1, 1, 5, 6, 2, 6, 4, 7, 3, 1, 8, 3, 3, 2, 6, 4, 6, 3, 6, 3],
       [4, 9, 2, 0, 2, 5, 9, 0, 5, 0, 5, 1, 6, 1, 6, 3, 3, 3, 0, 6],
       [8, 8, 1, 8, 1, 2, 7, 0, 9, 5, 2, 2, 0, 6, 6, 9, 9, 7, 7, 8]])