# 1 - Introdução a Matrizes 

In [1]:
# Importando o módulo numpy
import numpy as np

In [2]:
# Arrays numpy possuem N dimensões possíveis
array1 = np.random.randint(0, 11, size=(5, 5, 5)); array1

array([[[ 4,  2,  8,  6,  7],
        [ 8,  9,  0,  0,  9],
        [ 8, 10,  4,  0,  8],
        [ 3,  4,  3,  0,  1],
        [ 1,  9,  7,  7,  9]],

       [[ 0,  3,  4,  9,  5],
        [ 3, 10,  6,  5,  3],
        [ 9,  4,  5,  5,  1],
        [ 5,  2, 10,  8,  6],
        [ 1,  1,  5,  0,  8]],

       [[ 6,  8,  8,  5,  0],
        [10,  5,  1,  7,  7],
        [ 2,  2,  7,  8,  0],
        [ 6,  2,  8,  9,  8],
        [ 2,  4,  3, 10,  8]],

       [[ 4,  6,  2,  7,  0],
        [ 0, 10,  1,  4,  2],
        [ 2,  8,  3,  0,  6],
        [ 1,  2,  4,  3,  8],
        [10,  3,  7,  7,  5]],

       [[ 7,  3,  4,  4,  6],
        [ 7,  6,  5, 10,  5],
        [ 7,  9, 10, 10,  1],
        [ 1,  3,  8,  3,  4],
        [ 4,  9,  8, 10,  4]]])

In [3]:
# Matrizes numpy possuem restritamente 2 dimensões
matrix1 = np.matrix([[5, 2, 3], [1, 2, 3], [7, 8, 9]]); matrix1

matrix([[5, 2, 3],
        [1, 2, 3],
        [7, 8, 9]])

In [4]:
# Transposta da matriz
matrix1.T

matrix([[5, 1, 7],
        [2, 2, 8],
        [3, 3, 9]])

In [5]:
# Visualizando o tipo da matrix
type(matrix1)

numpy.matrix

In [6]:
# Inversa da matriz
matrix1.I

matrix([[ 0.25      , -0.25      ,  0.        ],
        [-0.5       , -1.        ,  0.5       ],
        [ 0.25      ,  1.08333333, -0.33333333]])

In [7]:
# Transposta Conjugada
matrix1.H

matrix([[5, 1, 7],
        [2, 2, 8],
        [3, 3, 9]])

In [8]:
# Gerando uma matriz indentidade
matrix1.I * matrix1

matrix([[ 1.00000000e+00,  1.11022302e-16,  2.22044605e-16],
        [-4.44089210e-16,  1.00000000e+00,  0.00000000e+00],
        [ 2.77555756e-16,  0.00000000e+00,  1.00000000e+00]])

# 2 - Operações com Matrizes

In [9]:
# Criando um array bidimensional
a = np.array([[1, 2], [4, 5]])
a

array([[1, 2],
       [4, 5]])

In [10]:
a * a

array([[ 1,  4],
       [16, 25]])

In [11]:
# Criando uma matriz
A = np.matrix(a)
A

matrix([[1, 2],
        [4, 5]])

In [12]:
A * A

matrix([[ 9, 12],
        [24, 33]])