<font size=6 color='green'> Entendendo a Classificação por Trás dos Panos </font>

---

# 1 - Primeiros Passos

## 1.1 - Importação da Base de Dados

In [1]:
# Importando bibliotecas inicialmente necessárias
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Importando a base de dados local
voz = pd.read_csv('/home/joeldspy/Modelos/datasets/churn.csv')

In [3]:
# Visualizando as 3 primeiras observações da base de dados
voz.head(3)

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo  \
0            0     Sim         Nao                1          Nao   
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline  \
0    SemServicoTelefonico               DSL             Nao          Sim   
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato  \
0                 Nao            Nao     Nao               Nao    Mensalmente   
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim

## 1.2 - Tratamentos de Dados

In [4]:
pd.value_counts(voz['Churn'])

Nao    5174
Sim    1869
Name: Churn, dtype: int64

In [5]:
# Separando e tratados dados binários
_ = {'Sim': 1, 'Nao' : 0}
bi_data = voz[['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn']].replace(_)
bi_data.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0        1            0             0                1      0
1        0            0             1                0      0
2        0            0             1                1      1
3        0            0             0                0      0
4        0            0             1                1      1

In [6]:
# Transformando valores categóricos em variáveis binárias
_ = voz.drop(columns=['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn'])
dummies_data = pd.get_dummies(_)
dummies_data.head()

Maior65Anos  MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0            0                1        29.85                            0   
1            0               34        56.95                            1   
2            0                2        53.85                            1   
3            0               45        42.30                            0   
4            0                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  VariasLinhasTelefonicas_Sim  \
0                                             1                            0   
1                                             0                            0   
2                                             0                            0   
3                                             1                            0   
4                                             0                            0   

   ServicoDeInternet_DSL  ServicoDeInternet_FibraOptica  \
0                      1                              0   
1                      1                              0   
2                      1                              0   
3                      1                              0   
4                      0                              1   

   ServicoDeInternet_Nao  SegurancaOnline_Nao  ...  StreamingDeFilmes_Nao  \
0                      0                    1  ...                      1   
1                      0                    0  ...                      1   
2                      0                    0  ...                      1   
3                      0                    0  ...                      1   
4                      0                    1  ...                      1   

   StreamingDeFilmes_SemServicoDeInternet  StreamingDeFilmes_Sim  \
0                                       0                      0   
1                                       0                      0   
2                                       0                      0   
3                                       0                      0   
4                                       0                      0   

   TipoDeContrato_DoisAnos  TipoDeContrato_Mensalmente  TipoDeContrato_UmAno  \
0                        0                           1                     0   
1                        0                           0                     1   
2                        0                           1                     0   
3                        0                           0                     1   
4                        0                           1                     0   

   FormaDePagamento_CartaoDeCredito  FormaDePagamento_ChequeDigital  \
0                                 0                               1   
1                                 0                               0   
2                                 0                               0   
3                                 0                               0   
4                                 0                               1   

   FormaDePagamento_ChequePapel  FormaDePagamento_DebitoEmConta  
0                             0                               0  
1                             1                               0  
2                             1                               0  
3                             0                               1  
4                             0                               0  

[5 rows x 34 columns]

In [7]:
# Gerando a base de dados final para treino do modelo
voz = pd.concat([bi_data, dummies_data], axis=1)
voz.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   
3               45        42.30                            0   
4                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  ...  StreamingDeFilmes_Nao  \
0                                             1  ...                      1   
1                                             0  ...                      1   
2                                             0  ...                      1   
3                                             1  ...                      1   
4                                             0  ...                      1   

   StreamingDeFilmes_SemServicoDeInternet  StreamingDeFilmes_Sim  \
0                                       0                      0   
1                                       0                      0   
2                                       0                      0   
3                                       0                      0   
4                                       0                      0   

   TipoDeContrato_DoisAnos  TipoDeContrato_Mensalmente  TipoDeContrato_UmAno  \
0                        0                           1                     0   
1                        0                           0                     1   
2                        0                           1                     0   
3                        0                           0                     1   
4                        0                           1                     0   

   FormaDePagamento_CartaoDeCredito  FormaDePagamento_ChequeDigital  \
0                                 0                               1   
1                                 0                               0   
2                                 0                               0   
3                                 0                               0   
4                                 0                               1   

   FormaDePagamento_ChequePapel  FormaDePagamento_DebitoEmConta  
0                             0                               0  
1                             1                               0  
2                             1                               0  
3                             0                               1  
4                             0                               0  

[5 rows x 39 columns]

In [8]:
voz.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 39 columns):
 #   Column                                        Non-Null Count  Dtype  
---  ------                                        --------------  -----  
 0   Conjuge                                       7043 non-null   int64  
 1   Dependentes                                   7043 non-null   int64  
 2   TelefoneFixo                                  7043 non-null   int64  
 3   PagamentoOnline                               7043 non-null   int64  
 4   Churn                                         7043 non-null   int64  
 5   Maior65Anos                                   7043 non-null   int64  
 6   MesesDeContrato                               7043 non-null   int64  
 7   ContaMensal                                   7043 non-null   float64
 8   VariasLinhasTelefonicas_Nao                   7043 non-null   uint8  
 9   VariasLinhasTelefonicas_SemServicoTelefonico  7043 non-null   u

# 2 - Aprendizado de Máquina

## 2.1 - Modelo KNeighborsClassifier

O K-Nearest Neighbors (KNN) é um algoritmo de aprendizado de máquina supervisionado utilizado para classificação e regressão. Ele é um dos algoritmos mais simples de serem entendidos e implementados.

A ideia principal por trás do KNN é que ele classifica ou faz predições com base na proximidade dos dados em um espaço de características. O algoritmo é chamado de "K-Nearest Neighbors" porque ele considera os K vizinhos mais próximos de um dado de entrada (ponto) para tomar uma decisão.

Aqui está uma explicação passo a passo de como o KNN funciona:

**Treinamento**: Durante a fase de treinamento do KNN, o algoritmo simplesmente armazena os dados de treinamento no conjunto de dados. Não há um processo de treinamento complexo ou cálculos de parâmetros como em outros algoritmos de aprendizado de máquina. O KNN é um algoritmo baseado em instância, o que significa que ele memoriza todos os dados de treinamento para serem usados posteriormente na fase de teste.

**Seleção de características e medida de distância**: O KNN usa um conjunto de características para medir a distância entre os pontos de dados. É importante escolher um conjunto adequado de características relevantes para o problema em questão, pois isso afetará a precisão do algoritmo. A medida de distância mais comumente usada é a distância Euclidiana, mas também é possível usar outras medidas de distância, como a distância de Manhattan ou a distância de Minkowski.

**Classificação ou predição**: Na fase de teste, o KNN recebe um novo ponto de entrada e calcula a distância dele em relação aos pontos de treinamento. Ele então seleciona os K pontos de treinamento mais próximos (os K vizinhos mais próximos) com base na medida de distância escolhida. A classe (ou valor de regressão) do novo ponto de entrada é determinada pela classe (ou valor de regressão) mais frequente entre os K vizinhos mais próximos. No caso de classificação, o KNN atribui a nova entrada à classe mais comum entre os vizinhos mais próximos. No caso de regressão, o KNN faz uma média dos valores de regressão dos K vizinhos mais próximos para estimar o valor de regressão da nova entrada.

**Escolha do valor de K**: A escolha do valor de K é importante no KNN, pois pode afetar a precisão do algoritmo. Um valor de K muito pequeno pode levar a uma classificação ou predição instável, enquanto um valor de K muito grande pode levar a uma perda de detalhes e informações locais. A escolha do valor de K geralmente é feita empiricamente ou usando técnicas de validação cruzada para encontrar o valor ótimo.

Em resumo, o KNN é um algoritmo simples e intuitivo que se baseia na proximidade dos dados para fazer classificação ou predição. Ele é amplamente utilizado em problemas de classificação e regressão, mas também tem algumas limitações, como a sensibilidade a ruídos e a necessidade de escolher adequadamente o valor de K.


![KNN](https://www.theclickreader.com/wp-content/uploads/2020/08/23-1024x576.png)

In [9]:
# Separando dados entra extrada e saída
x = voz.drop(columns=['Churn'])
y = voz['Churn']

In [10]:
# Definindo os dados de um novo cliente
new_client = [[0,0,1,1,0,0,39.90,1,0,0,0,1,0,1,0,0,0,0,1,1,1,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,1]]

In [12]:
# Normalizando a base de dados
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(x)

x_norm = scaler.transform(x)
new_client = scaler.transform(new_client)

<font size=6> $$ Z = \frac{x - \mu}{\sigma} $$

In [15]:
# Definindo pontos para calcular a distância
point_a = x_norm[0]
point_b = new_client

<font size=5> $$d(\mathbf{p}, \mathbf{q}) = \sqrt{\sum_{i=1}^{N} (p_i - q_i)^2}$$ </font>

In [16]:
# Distância do novo cliente para o cliente de index 0 
np.sqrt(np.sum(np.square(point_a - point_b)))

9.169282435541762

In [17]:
# Calculando a distância para cada cliente na base de dados
def euclidean_distance(point_a, point_b):
    return np.sqrt(np.sum(np.square(point_a - point_b)))

distances = []
for client in x_norm:
    distance = euclidean_distance(client, new_client)
    distances.append(distance)

distances = pd.DataFrame(zip(distances, range(0, len(distances), 1)))
distances.columns = ['distances', 'index']
distances['target'] = y 
distances.head()

distances  index  target
0   9.169282      0       0
1   8.742314      1       0
2   7.961048      2       1
3   9.683687      3       0
4   7.357567      4       1

In [18]:
# Os 5 clientes mais próximos
distances.sort_values(by='distances')[:5]

distances  index  target
907    5.142441    907       0
205    5.348893    205       0
4422   5.410621   4422       0
3744   5.553469   3744       0
758    5.774714    758       1

In [19]:
# Separando dados entre treino e teste
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_norm, y, test_size=0.25)

In [21]:
# Predizendo a classe do novo cliente
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3, metric='euclidean')

knn.fit(x_train, y_train)

knn.predict(new_client)

array([0])

In [22]:
# Acurácia em todos os dados de teste
from sklearn.metrics import accuracy_score

y_pred = knn.predict(x_test)
accuracy = accuracy_score(y_pred, y_test)

print('Tamanho dos dados de treino: %d' % len(x_train))
print('Tamanho dos dados de teste: %d' % len(x_test))
print('A acurácia do modelo KNeighborsClassifier foi de %.2f%%' % (accuracy * 100))

Tamanho dos dados de treino: 5282
Tamanho dos dados de teste: 1761
A acurácia do modelo KNeighborsClassifier foi de 73.76%


## 2.2 - Modelo Baseado no Teorema de Naive Bayes
O Teorema de Naive Bayes é um algoritmo de aprendizado de máquina que é usado para classificação de dados. Ele é baseado na aplicação do teorema de Bayes, que é uma fórmula matemática que nos permite calcular a probabilidade de um evento ocorrer, dado que outro evento já ocorreu.

O "naive" em Naive Bayes se refere a uma suposição simplificada que o algoritmo faz, que é a de que as características dos dados são independentes entre si. Isso significa que o valor de uma característica não é influenciado pelo valor de outra característica, o que nem sempre é verdade em situações do mundo real. Apesar dessa suposição simplificada, o Naive Bayes pode ser surpreendentemente eficaz em muitos cenários de classificação de dados.

Em termos simples, o Teorema de Naive Bayes é usado para calcular a probabilidade de um dado ponto de dados pertencer a uma determinada classe, com base na probabilidade das características desse dado ponto de dados ocorrerem em cada classe. É usado para classificar dados em categorias com base na probabilidade de ocorrência dessas categorias, dadas as características dos dados. É amplamente utilizado em tarefas de classificação de texto, como análise de sentimentos, detecção de spam e categorização de notícias, entre outras aplicações.

<font size=5> $$P(B|A) = \frac{P(B) \cdot P(A|B)}{P(A)}$$

In [23]:
# Separando dados entre treino e teste
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_norm, y, test_size=0.25)

In [24]:
from sklearn.naive_bayes import BernoulliNB

bnb = BernoulliNB(binarize=abs(np.median(x_train)))

bnb.fit(x_train, y_train)

bnb.predict(new_client)

array([0])

In [25]:
from sklearn.metrics import accuracy_score

y_pred = bnb.predict(x_test)
accuracy = accuracy_score(y_pred, y_test)

print('Tamanho dos dados de treino: %d' % len(x_train))
print('Tamanho dos dados de teste: %d' % len(x_test))
print('A acurácia do modelo KNeighborsClassifier foi de %.2f%%' % (accuracy * 100))

Tamanho dos dados de treino: 5282
Tamanho dos dados de teste: 1761
A acurácia do modelo KNeighborsClassifier foi de 72.29%


## 2.3 - Modelo de Árvore de Decisão

A árvore de decisão é um método de análise de dados que é usado para tomar decisões ou fazer previsões com base em regras de decisão hierárquicas. É uma técnica de aprendizado de máquina supervisionado que pode ser usada tanto para problemas de classificação quanto de regressão.

A construção de uma árvore de decisão envolve dividir os dados de treinamento em subconjuntos com base nos valores dos atributos, seguindo uma estrutura de árvore. A cada passo, o algoritmo de árvore de decisão seleciona o atributo mais relevante para dividir os dados em subconjuntos, com base em uma métrica de impureza, como a entropia ou o índice de Gini. A ideia é dividir os dados de forma a criar subconjuntos mais homogêneos em relação à classe de destino (no caso de classificação) ou à variável de destino (no caso de regressão).

Essa divisão é repetida recursivamente até que sejam alcançados critérios de parada, como profundidade máxima da árvore ou número mínimo de amostras em um nó. A árvore de decisão resultante é uma estrutura hierárquica de nós, onde cada nó representa uma decisão com base em um atributo, e as folhas da árvore representam as classes ou os valores de regressão previstos.

Uma vez que a árvore de decisão tenha sido construída, ela pode ser usada para fazer previsões em novos dados, seguindo as decisões tomadas em cada nó da árvore até chegar a uma folha, onde a classe ou valor de regressão é previsto.

As árvores de decisão são populares porque são fáceis de interpretar e visualizar, e podem ser aplicadas a uma ampla variedade de problemas. No entanto, assim como as árvores de cisão, as árvores de decisão podem ser suscetíveis a overfitting, e técnicas de melhoria, como a poda de árvore ou o uso de variantes como o Random Forest e o Gradient Boosting, podem ser aplicadas para melhorar seu desempenho.

![Árvore de Decisão](https://lh4.googleusercontent.com/gLv2IKMo4gpmcNSw-C4FuPOoL9rwsFF0k1_naUf9AxnXRzYKLrFvdzoO81qWmpLA2CiP55Uxks3JIBzWBXcvkLODdKoQ1emKNZKyhU1iKQjSFGDT6l9-RCTYNth9mt2_VhOzolI)

In [26]:
# Separando dados entre treino e teste
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_norm, y, test_size=0.25)

In [36]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier(max_depth=2)

dtc.fit(x_train, y_train)

dtc.predict(new_client)

array([0])

In [37]:
from sklearn.metrics import accuracy_score

y_pred = dtc.predict(x_test)
accuracy = accuracy_score(y_pred, y_test)

print('Tamanho dos dados de treino: %d' % len(x_train))
print('Tamanho dos dados de teste: %d' % len(x_test))
print('A acurácia do modelo KNeighborsClassifier foi de %.2f%%' % (accuracy * 100))

Tamanho dos dados de treino: 5282
Tamanho dos dados de teste: 1761
A acurácia do modelo KNeighborsClassifier foi de 75.81%


# 3 - Métricas de Validação

## 3.1 - Matriz de Confusão

![Matriz de Confusão](https://diegonogare.net/wp-content/uploads/2020/04/matrizConfusao-600x381.png)

In [39]:
# Separando dados entre treino e teste
np.random.seed(85)

x_train, x_test, y_train, y_test = train_test_split(x_norm, y, test_size=0.25)

dtc = DecisionTreeClassifier()

dtc.fit(x_train, y_train)

bnb = BernoulliNB(binarize=abs(np.median(x_train)))

bnb.fit(x_train, y_train)

knn = KNeighborsClassifier(metric='euclidean')

knn.fit(x_train, y_train)

KNeighborsClassifier(metric='euclidean')

In [40]:
from sklearn import metrics

knn_predict = knn.predict(x_test)
bnb_predict = bnb.predict(x_test)
dtc_predict = dtc.predict(x_test)

knn_matrix = metrics.confusion_matrix(y_test, knn_predict)
bnb_matrix = metrics.confusion_matrix(y_test, bnb_predict)
dtc_matrix = metrics.confusion_matrix(y_test, dtc_predict)

In [41]:
knn_matrix

array([[1106,  205],
       [ 229,  221]])

In [42]:
bnb_matrix

array([[899, 412],
       [ 88, 362]])

In [43]:
dtc_matrix

array([[1059,  252],
       [ 229,  221]])

## 3.2 - Acurácia

In [44]:
accuracy_score(y_test, knn_predict)

0.7535491198182851

In [45]:
accuracy_score(y_test, bnb_predict)

0.7160704145371948

In [46]:
accuracy_score(y_test, dtc_predict)

0.7268597387847814

## 3.3 - Precisão

In [47]:
metrics.precision_score(y_test, knn_predict)

0.5187793427230047

In [48]:
metrics.precision_score(y_test, bnb_predict)

0.46770025839793283

In [49]:
metrics.precision_score(y_test, dtc_predict)

0.46723044397463004

## 3.4 - Recall

In [50]:
metrics.recall_score(y_test, knn_predict)

0.4911111111111111

In [51]:
metrics.recall_score(y_test, bnb_predict)

0.8044444444444444

In [52]:
metrics.recall_score(y_test, dtc_predict)

0.4911111111111111