# <font color='green'> Aprendendo Machine Learning Através de um Projeto </font>

# 1 - Primeiras Impressões

## 1.1 - Importando Base de Dados

In [1]:
# Importando módulos necessários
import pandas as pd
import numpy as np
import warnings

In [2]:
# Desativando possíveis avisos
warnings.filterwarnings('ignore')

In [3]:
# Importando a base de dados
telecom = pd.read_csv('/home/joeldspy/Modelos/datasets/churn.csv')

In [4]:
# Dimensões da nossa base de dados
telecom.shape

(7043, 18)

In [5]:
# Primeiras impressões do nosso dataset
telecom.head(3)

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo  \
0            0     Sim         Nao                1          Nao   
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline  \
0    SemServicoTelefonico               DSL             Nao          Sim   
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato  \
0                 Nao            Nao     Nao               Nao    Mensalmente   
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim

## 1.2 - Tratando a Base de Dados

In [6]:
# Algumas informações da base de dados crua
telecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Maior65Anos              7043 non-null   int64  
 1   Conjuge                  7043 non-null   object 
 2   Dependentes              7043 non-null   object 
 3   MesesDeContrato          7043 non-null   int64  
 4   TelefoneFixo             7043 non-null   object 
 5   VariasLinhasTelefonicas  7043 non-null   object 
 6   ServicoDeInternet        7043 non-null   object 
 7   SegurancaOnline          7043 non-null   object 
 8   BackupOnline             7043 non-null   object 
 9   SeguroNoDispositivo      7043 non-null   object 
 10  SuporteTecnico           7043 non-null   object 
 11  TVaCabo                  7043 non-null   object 
 12  StreamingDeFilmes        7043 non-null   object 
 13  TipoDeContrato           7043 non-null   object 
 14  PagamentoOnline         

In [7]:
# Acessando os dados binários
bi_data = telecom[['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn']]
bi_data.head(3)

Conjuge Dependentes TelefoneFixo PagamentoOnline Churn
0     Sim         Nao          Nao             Sim   Nao
1     Nao         Nao          Sim             Nao   Nao
2     Nao         Nao          Sim             Sim   Sim

In [8]:
# Modificando os dados binários
bi_data = bi_data.replace({'Sim' : 1, 'Nao' : 0})
bi_data.head(3)

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0        1            0             0                1      0
1        0            0             1                0      0
2        0            0             1                1      1

In [9]:
# Transformando variáveis qualitativas em variáveis binárias
dummies_data = pd.get_dummies(telecom.drop(bi_data.columns, axis=1))
dummies_data.head(3)

Maior65Anos  MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0            0                1        29.85                            0   
1            0               34        56.95                            1   
2            0                2        53.85                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  VariasLinhasTelefonicas_Sim  \
0                                             1                            0   
1                                             0                            0   
2                                             0                            0   

   ServicoDeInternet_DSL  ServicoDeInternet_FibraOptica  \
0                      1                              0   
1                      1                              0   
2                      1                              0   

   ServicoDeInternet_Nao  SegurancaOnline_Nao  ...  StreamingDeFilmes_Nao  \
0                      0                    1  ...                      1   
1                      0                    0  ...                      1   
2                      0                    0  ...                      1   

   StreamingDeFilmes_SemServicoDeInternet  StreamingDeFilmes_Sim  \
0                                       0                      0   
1                                       0                      0   
2                                       0                      0   

   TipoDeContrato_DoisAnos  TipoDeContrato_Mensalmente  TipoDeContrato_UmAno  \
0                        0                           1                     0   
1                        0                           0                     1   
2                        0                           1                     0   

   FormaDePagamento_CartaoDeCredito  FormaDePagamento_ChequeDigital  \
0                                 0                               1   
1                                 0                               0   
2                                 0                               0   

   FormaDePagamento_ChequePapel  FormaDePagamento_DebitoEmConta  
0                             0                               0  
1                             1                               0  
2                             1                               0  

[3 rows x 34 columns]

In [10]:
# Concatenando os 2 datasets
telecom = pd.concat([bi_data, dummies_data], axis=1)

In [11]:
# Visualizando o dataset final
telecom.head(3)

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  ...  StreamingDeFilmes_Nao  \
0                                             1  ...                      1   
1                                             0  ...                      1   
2                                             0  ...                      1   

   StreamingDeFilmes_SemServicoDeInternet  StreamingDeFilmes_Sim  \
0                                       0                      0   
1                                       0                      0   
2                                       0                      0   

   TipoDeContrato_DoisAnos  TipoDeContrato_Mensalmente  TipoDeContrato_UmAno  \
0                        0                           1                     0   
1                        0                           0                     1   
2                        0                           1                     0   

   FormaDePagamento_CartaoDeCredito  FormaDePagamento_ChequeDigital  \
0                                 0                               1   
1                                 0                               0   
2                                 0                               0   

   FormaDePagamento_ChequePapel  FormaDePagamento_DebitoEmConta  
0                             0                               0  
1                             1                               0  
2                             1                               0  

[3 rows x 39 columns]

# 2 - Criando Modelos de Machine Learning

## 2.1 - Distância Euclidiana

In [12]:
# Separando dados entre entrada e saída
x = telecom.drop(['Churn'], axis=1)
y = telecom['Churn']

In [13]:
# Normalizando os dados
from sklearn.preprocessing import StandardScaler
st_scaler = StandardScaler()
x_norm = st_scaler.fit_transform(x)

### $$ d = \sqrt{\sum_{i=1}^{n} (x_i - y_i)^2} $$

In [14]:
# Definindo dois pontos
point_a = x_norm[0]
point_b = st_scaler.transform([[0,0,1,1,0,0,39.90,1,0,0,0,1,0,0,0,0,1,1,1,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,1,0,1,0]])

In [15]:
# Elevando ao quadrado a diferença de todas as dimensões entre pontos
np.square(point_a - point_b)

array([[4.00461149e+00, 0.00000000e+00, 1.14341953e+01, 0.00000000e+00,
        0.00000000e+00, 1.65814802e-03, 1.11570160e-01, 4.00558550e+00,
        1.14341953e+01, 0.00000000e+00, 4.43292768e+00, 4.05926401e+00,
        0.00000000e+00, 4.00017814e+00, 0.00000000e+00, 0.00000000e+00,
        4.06154807e+00, 5.89193381e+00, 0.00000000e+00, 4.05954705e+00,
        0.00000000e+00, 4.43205631e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 4.17023749e+00, 0.00000000e+00, 4.22608130e+00,
        4.18296779e+00, 0.00000000e+00, 4.21169253e+00, 0.00000000e+00,
        4.04071758e+00, 0.00000000e+00, 5.90313856e+00, 4.48357062e+00,
        5.66592128e+00, 0.00000000e+00]])

In [16]:
# Somando os quadrados das diferenças
np.sum(np.square(point_a - point_b))

98.81359814827535

In [17]:
# Extraindo a raiz quadrada
np.sqrt(np.sum(np.square(point_a - point_b)))

9.940502912241179

## 2.2 - Criando Modelos

In [18]:
# Separando dados de treino e teste
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_norm, y, random_state=75, train_size=0.25)

<div align='center'>
<img src='https://www.jcchouinard.com/wp-content/uploads/2021/08/image-8.png'>
</div>

In [19]:
# Criando modelo de KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean')

knn.fit(x_train, y_train)

print(f'A acurácia do modelo KNeighborsClassifier foi de {knn.score(x_test, y_test):.2f}')

A acurácia do modelo KNeighborsClassifier foi de 0.75


<div align='center'>
<img src='https://scikit-learn.org/0.20/_images/sphx_glr_plot_random_forest_embedding_thumb.png'>
</div>

In [26]:
# Criando modelo de BernoulliNB
from sklearn.naive_bayes import BernoulliNB

bnb = BernoulliNB()

bnb.fit(x_train, y_train)

print(f'A acurácia do modelo BernoulliNB foi de {bnb.score(x_test, y_test):.2f}')

A acurácia do modelo BernoulliNB foi de 0.72


In [21]:
# Gerando dados preditos de ambos os modelos
knn_pred = knn.predict(x_test)
bnb_pred = bnb.predict(x_test)

In [22]:
# Avaliando métricas
from sklearn.metrics import confusion_matrix

In [23]:
# Matriz de confusão do modelo KNeighborsClassifier
confusion_matrix(y_test, knn_pred)

array([[3223,  650],
       [ 670,  740]])

In [24]:
# Matriz de confusão do modelo BernoulliNB
confusion_matrix(y_test, bnb_pred)

array([[2658, 1215],
       [ 269, 1141]])