In [41]:
# Importando o módulo numpy
import numpy as np

In [27]:
# Arrays numpy possuem N dimensões possíveis
array1 = np.random.randint(0, 11, size=(5, 5, 5)); array1

array([[[ 1,  0,  3,  6,  0],
        [10,  0,  6,  9,  9],
        [ 3,  8,  0,  9,  8],
        [ 2,  9,  4,  0,  3],
        [ 6,  3,  2,  1,  5]],

       [[ 6,  8,  7,  1,  4],
        [ 8,  0,  6, 10,  8],
        [ 1,  8,  6,  3,  0],
        [ 2,  8,  7,  8,  0],
        [ 4, 10,  2,  8,  0]],

       [[ 5,  1,  5,  1,  6],
        [ 6,  0,  4,  2,  9],
        [ 9,  2,  2,  3,  5],
        [ 7,  4,  0,  6,  1],
        [10,  8,  3,  2,  8]],

       [[10,  8,  1,  4,  8],
        [ 1,  5,  1,  2,  6],
        [ 1,  5,  3,  4,  6],
        [ 4,  1,  9,  6,  2],
        [ 7,  4,  6,  8,  0]],

       [[ 8,  3,  6,  9, 10],
        [ 8,  9,  1,  9,  0],
        [ 9,  8,  8,  0,  5],
        [ 0,  0,  5,  5,  5],
        [ 3,  8,  0,  4,  4]]])

In [32]:
# Matrizes numpy possuem restritamente 2 dimensões
matrix1 = np.matrix([[5, 2, 3], [1, 2, 3], [7, 8, 9]]); matrix1

matrix([[5, 2, 3],
        [1, 2, 3],
        [7, 8, 9]])

In [33]:
# Transposta da matriz
matrix1.T

matrix([[5, 1, 7],
        [2, 2, 8],
        [3, 3, 9]])

In [34]:
# Inversa da matriz
matrix1.I

matrix([[ 0.25      , -0.25      ,  0.        ],
        [-0.5       , -1.        ,  0.5       ],
        [ 0.25      ,  1.08333333, -0.33333333]])

In [39]:
# Transposta Conjugada
matrix1.H

matrix([[5, 1, 7],
        [2, 2, 8],
        [3, 3, 9]])

In [38]:
# Gerando uma matriz indentidade
matrix1.I * matrix1

matrix([[ 1.00000000e+00,  1.11022302e-16,  2.22044605e-16],
        [-4.44089210e-16,  1.00000000e+00,  0.00000000e+00],
        [ 2.77555756e-16,  0.00000000e+00,  1.00000000e+00]])